-- phpMyAdmin SQL Dump
-- version 4.2.12deb2
-- http://www.phpmyadmin.net
--
-- Värd: blu-ray.student.bth.se
-- Tid vid skapande: 02 okt 2015 kl 19:14
-- Serverversion: 5.5.44-0+deb8u1-log
-- PHP-version: 5.6.13-0+deb8u1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Databas: `sios13`
--

-- --------------------------------------------------------

--
-- Tabellstruktur `kmom07_Content`
--

CREATE TABLE IF NOT EXISTS `kmom07_Content` (
`id` int(11) NOT NULL,
  `slug` char(80) DEFAULT NULL,
  `url` char(80) DEFAULT NULL,
  `type` char(80) DEFAULT NULL,
  `title` varchar(80) DEFAULT NULL,
  `data` text,
  `category` varchar(80) DEFAULT NULL,
  `filter` char(80) DEFAULT NULL,
  `published` datetime DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `updated` datetime DEFAULT NULL,
  `deleted` datetime DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;

--
-- Dumpning av Data i tabell `kmom07_Content`
--

INSERT INTO `kmom07_Content` (`id`, `slug`, `url`, `type`, `title`, `data`, `category`, `filter`, `published`, `created`, `updated`, `deleted`) VALUES
(1, 'om', 'om', 'page', 'Om', 'Om Rental Movies\n=======\n\nDenna webbplats är skapad av Simon Österdahl som ett projekt i kursen oophp.', '', 'markdown', '2014-01-15 12:58:41', '2014-01-15 12:58:41', NULL, NULL),
(2, 'v-lkommen-till-min-blogg', NULL, 'post', 'Välkommen till min blogg!', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut tellus vitae nunc vulputate lobortis at quis mauris. Nullam cursus quis mi sed ultricies. Integer interdum volutpat enim, id pretium nisl tristique vel. Aliquam erat volutpat. Quisque libero mauris, convallis et dignissim eu, sollicitudin in lorem. Vestibulum interdum odio at ante rutrum elementum. Proin sit amet lectus eros.\n\nMauris viverra pretium sapien nec malesuada. Mauris iaculis turpis a sem pharetra, ut venenatis nunc vestibulum. Integer eu consectetur orci, sit amet rhoncus libero. Pellentesque laoreet, lectus id dictum fermentum, eros nunc molestie augue, ac auctor tortor diam ut orci. Aliquam quis adipiscing nibh, vel iaculis metus. Nunc suscipit ullamcorper sapien egestas posuere. Curabitur in varius enim. Vivamus iaculis massa nisl, vitae cursus eros luctus quis. Nam cursus erat purus, ornare pellentesque metus mattis quis. In vestibulum ultrices varius. Quisque eros massa, tincidunt ac sem vitae, viverra feugiat felis. Nulla varius sagittis ipsum sit amet lacinia. Proin eu felis adipiscing, viverra purus ac, laoreet odio.\n\nDonec malesuada interdum vulputate. Etiam nec eleifend justo. Nulla tincidunt nulla non iaculis euismod. Donec bibendum, tortor in pulvinar bibendum, justo orci suscipit odio, non pellentesque augue tellus condimentum elit. Suspendisse lacinia magna id diam pellentesque, eleifend eleifend nisi rhoncus. Etiam hendrerit tincidunt lectus, vel tincidunt lorem egestas nec. Phasellus laoreet ante vulputate, ornare tellus imperdiet, rhoncus velit. Cras nec diam lacinia, auctor dolor non, ultricies arcu. Ut nec ante semper, ultricies augue et, laoreet sapien. Donec ullamcorper et justo sit amet condimentum. Integer sit amet diam eu metus sollicitudin porta quis et magna.', 'foto, film', 'nl2br', '2014-01-15 12:58:41', '2014-01-15 12:58:41', NULL, NULL),
(3, 'en-j-ttebra-film', NULL, 'post', 'En jättebra film', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin commodo augue tincidunt dui venenatis rhoncus vitae ut purus. Fusce dignissim sem ac quam consequat convallis. Aliquam cursus laoreet metus nec laoreet. Pellentesque sed felis nec justo porta accumsan vel ut tellus. Integer et tempor odio. Phasellus eu libero augue. Curabitur mauris urna, commodo non elit non, faucibus fringilla velit. Quisque urna urna, fermentum non accumsan vel, dictum condimentum tortor.\n\nAliquam dictum blandit metus non convallis. Integer adipiscing orci mi, et facilisis eros tempus sed. Quisque diam leo, dignissim at lobortis eget, gravida eget neque. Ut in nulla pretium, ornare justo eget, condimentum libero. Mauris vitae ipsum mi. Ut molestie, dolor ut cursus viverra, arcu turpis accumsan neque, vitae suscipit massa massa eu ligula. Donec malesuada in magna sit amet tincidunt.\n\nDuis massa magna, vehicula vitae arcu eu, vehicula tristique tellus. In hac habitasse platea dictumst. Nulla lobortis mauris vel libero suscipit sagittis. Mauris aliquet magna non massa elementum, in rutrum sapien pharetra. Vestibulum vel commodo tellus. Sed feugiat dolor sit amet leo facilisis, eget convallis turpis mollis. Maecenas tellus nulla, interdum et placerat pulvinar, sollicitudin vitae elit. Phasellus eleifend erat luctus, fringilla ante nec, convallis orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi mattis blandit leo vel pulvinar. Maecenas blandit, leo at molestie iaculis, purus risus laoreet libero, eu ullamcorper orci odio at nunc.', 'foto, film', 'nl2br', '2014-01-15 12:58:41', '2014-01-15 12:58:41', NULL, NULL),
(4, 'g-stinl-gg-fr-n-james-bond', NULL, 'post', 'Gästinlägg från James Bond', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam purus metus, accumsan quis lectus id, rutrum scelerisque risus. Duis venenatis neque eros, sit amet tristique magna tincidunt eget. Mauris lacinia, ipsum vel fringilla auctor, nisl metus ullamcorper odio, vel rutrum mi urna sed lorem. Vivamus id ipsum facilisis, pellentesque sapien vitae, pellentesque libero. Ut in porta nisi. Quisque auctor mattis lobortis. Proin in enim velit. Nam pulvinar vehicula gravida. Phasellus id lectus et odio suscipit varius. Aenean semper dapibus commodo. Aliquam velit libero, pellentesque in eleifend sed, ullamcorper a velit. Cras sed libero at libero luctus congue. Nullam commodo auctor consequat. Curabitur imperdiet quis tortor vitae commodo. Phasellus vel scelerisque nisl. Phasellus erat metus, interdum id feugiat in, consectetur a odio.\n\nSed ut ligula volutpat, mollis mi ut, dignissim neque. Phasellus fermentum a lacus pulvinar elementum. Integer laoreet diam non fringilla aliquet. Ut eget neque sodales, pellentesque erat vel, euismod ipsum. Mauris ut neque at nunc tristique elementum. Vestibulum dui leo, lacinia vel egestas at, ornare sed risus. Nunc pharetra, sem ut consectetur posuere, lacus elit imperdiet nunc, sed convallis purus risus in nisl. Etiam iaculis ultricies massa non fermentum. Mauris venenatis, tellus non condimentum semper, sem leo imperdiet mauris, vitae porttitor augue lacus ut odio. Morbi rutrum et velit sit amet pellentesque. Aliquam sem risus, aliquet eu tellus et, vulputate volutpat purus.\n\nVestibulum facilisis eros nec bibendum consectetur. Aenean vel eros venenatis, sollicitudin orci sit amet, mollis tortor. Praesent vehicula imperdiet molestie. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris at mollis orci. Sed vestibulum ipsum quis leo volutpat dignissim. Phasellus lectus purus, cursus ut fermentum sed, hendrerit eu ipsum. Duis bibendum nulla ut nibh placerat volutpat. Phasellus in eros arcu. In interdum risus vel nisl fermentum placerat. Aenean pharetra justo a neque tempus vestibulum. Integer eu mauris vel leo accumsan semper. Quisque at elit nisi. Integer malesuada suscipit nibh, eu pretium metus ornare id. Donec commodo pharetra nunc, nec molestie tellus cursus quis.', 'foto, film', 'nl2br', '2014-01-15 12:58:41', '2014-01-15 12:58:41', NULL, NULL),
(5, 'tv-nya-filmer', NULL, 'post', 'Två nya filmer', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel sodales orci. Nullam quis massa quis lorem iaculis scelerisque. Pellentesque in ipsum in mi posuere lacinia. Nunc vulputate eros sapien, eget rutrum tellus vehicula a. Nullam mollis ante vel sodales adipiscing. Cras volutpat varius condimentum. In tincidunt risus at turpis suscipit mollis quis id tortor. Praesent dictum sagittis eros quis dictum. Maecenas justo ante, consequat nec lobortis vel, fermentum tincidunt diam. Aenean id varius quam. In interdum, dolor sed consectetur dapibus, ante magna ornare nisl, non ultricies lorem leo vitae augue. Integer consectetur ipsum quis volutpat iaculis.\n\nPhasellus ultricies nisi justo, vel ultricies arcu cursus id. Proin viverra, turpis sed facilisis dignissim, nunc ante fringilla tortor, eget suscipit leo leo a nisi. Pellentesque a metus in quam faucibus dictum. Nam fringilla, sem et commodo dictum, risus elit sodales sapien, eu pulvinar quam quam quis ligula. Nam rhoncus turpis hendrerit fringilla sollicitudin. Suspendisse lobortis aliquet pulvinar. Curabitur dictum pharetra mollis. Phasellus euismod felis nec velit ultricies, eu vulputate sem tempus. Integer at feugiat quam. Praesent non quam at metus tempus placerat at et dui. Phasellus malesuada nisl ante, non commodo lectus pellentesque sed. Aliquam convallis hendrerit tortor a tincidunt.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent euismod dui eu sapien fringilla, ac interdum diam accumsan. Aenean pulvinar risus a diam fringilla, eget tempor velit tempus. Duis volutpat elit vitae venenatis posuere. Nunc cursus justo et risus gravida mattis. Nulla facilisi. Nunc id tortor eget tellus placerat consectetur eu in lectus. Nunc nec arcu odio. Suspendisse quis erat urna. Donec aliquam dignissim augue, quis volutpat mi ultricies at. Cras vestibulum erat nec placerat posuere. Cras vel volutpat arcu, eleifend ornare dui.', 'foto, film', 'nl2br', '2014-01-15 12:58:41', '2014-01-15 12:58:41', NULL, NULL),
(6, 'en-recension', NULL, 'post', 'En recension', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sed tristique mi. Cras ut arcu pharetra, adipiscing urna in, eleifend eros. Nam rhoncus turpis at felis varius condimentum. Proin sed dignissim dui. Cras non adipiscing mi. In at varius magna. Curabitur a aliquam enim, eget tempus ante. Donec elementum magna vel arcu semper, ac vehicula urna eleifend.\n\nCras quis nisl sit amet ligula dapibus elementum vel quis eros. Nunc adipiscing porta nisl at mollis. Sed laoreet lacinia nibh, sit amet sollicitudin leo feugiat ac. Nulla nulla dolor, congue sed aliquam non, lobortis nec ligula. Sed nec blandit urna, sit amet pharetra metus. Fusce malesuada felis enim, vel mollis lectus vestibulum vel. Cras consequat est quis feugiat aliquam. Fusce eleifend imperdiet sem sed feugiat. In tincidunt vel justo at tincidunt. Sed at orci non lacus pulvinar aliquet eu et ipsum. Suspendisse rutrum auctor nunc, id tristique sapien luctus non. Quisque id convallis libero, quis dignissim risus. Duis condimentum vel turpis quis pulvinar. Morbi sagittis orci sed urna ultrices, at luctus erat lacinia. Donec eget dui augue.\n\nNam eget lacus feugiat, congue tellus sit amet, scelerisque magna. Sed non blandit sem. Mauris id ultricies eros, eu sodales urna. Vestibulum sit amet velit mauris. In vestibulum augue ac leo placerat, ut convallis nulla lacinia. Aenean sit amet justo eros. Mauris in ultricies libero.', 'foto, film', 'nl2br', '2014-01-15 12:58:41', '2014-01-15 12:58:41', NULL, NULL),
(7, 'g-p-bio', NULL, 'post', 'Gå på bio', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in fermentum ipsum, ut mollis felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed odio eros, viverra et justo ac, gravida adipiscing nisl. Vestibulum et turpis sed lorem condimentum ullamcorper ac sed orci. Integer condimentum aliquam augue. Nulla dignissim erat vitae ipsum auctor, id pharetra turpis venenatis. Quisque at enim tellus. Integer eget euismod dolor. Maecenas in sem eget orci dignissim blandit vitae nec dui. Aliquam aliquet lorem eu lobortis commodo. Nullam et cursus augue.\n\nFusce ac felis non felis gravida interdum. Etiam in egestas massa. Mauris luctus est ac laoreet gravida. Mauris neque elit, dictum nec ipsum in, feugiat consectetur metus. Morbi gravida justo blandit mi auctor, sed porttitor ligula tincidunt. Aliquam posuere enim non velit porta, nec adipiscing urna tincidunt. Quisque non justo at elit fringilla mattis ac nec nunc. Donec ut ipsum sit amet lectus iaculis sollicitudin. Etiam porta lacus rutrum, sodales magna ac, volutpat odio. Nam ullamcorper justo quis pellentesque suscipit. Praesent aliquet euismod justo, et fringilla nisi accumsan ut. Etiam porttitor, nunc sed bibendum viverra, est sapien vestibulum libero, id malesuada erat libero eget erat. Phasellus gravida, tellus eget venenatis imperdiet, dolor augue bibendum metus, eu consequat tellus ipsum in nibh.\n\nDonec fringilla congue orci sed pretium. Pellentesque et mattis nisi. Nulla sit amet malesuada risus. Aenean aliquam urna ac lacinia hendrerit. Vestibulum non sapien elit. Etiam ac aliquam nibh. Donec auctor nulla vel semper consequat. Aliquam ut pretium sapien, vitae blandit ligula. Nullam gravida risus nunc, at consectetur lectus condimentum eu. Praesent nisl felis, sodales eu dapibus a, congue ac quam.', 'spel, sport, it, film, debatt', 'nl2br', '2014-01-15 12:58:41', '2014-01-15 12:58:41', NULL, NULL),
(8, 'kolla-p-film', NULL, 'post', 'Kolla på film', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam et mi vitae diam vulputate feugiat pulvinar vitae ante. Etiam semper elit odio, dapibus consectetur massa laoreet id. Quisque ultrices diam pretium ante dignissim, sed egestas ante iaculis. Nulla congue augue id ipsum feugiat, eget cursus eros commodo. In venenatis tortor id mollis laoreet. Nullam sit amet metus sit amet libero auctor dignissim. Duis et rhoncus lorem, ac pharetra nibh. Quisque sodales ante mollis elit commodo, id volutpat dui aliquam. Nam auctor dui massa, a blandit urna blandit vitae. Aliquam fermentum felis quis justo venenatis pharetra. Ut augue justo, tempus quis elementum aliquet, hendrerit ut libero. Duis enim lectus, gravida convallis egestas sed, consectetur ac nunc. Donec eu aliquam tellus. Fusce ullamcorper, libero eget ultrices tempus, nunc nulla ultricies neque, at porta leo velit nec est. Aliquam vel nunc mollis, venenatis odio ut, mattis diam.\n\nNullam turpis arcu, consectetur quis aliquet id, mattis ac mauris. Nam semper lacus ultrices lacinia vestibulum. Nunc tempus, purus non tristique condimentum, tellus lorem pretium dui, eget hendrerit quam odio fringilla nisi. Vivamus nec quam sed urna congue ornare. Nullam quis tortor vestibulum, pellentesque velit et, varius erat. Fusce auctor ultricies diam, ac sagittis nisi blandit id. Duis facilisis arcu at sapien faucibus lacinia. Sed quis eros velit. Quisque scelerisque risus magna. Vestibulum feugiat ligula nulla, fringilla accumsan diam faucibus eu. Nunc lorem lectus, elementum nec scelerisque ac, auctor a enim.\n\nNullam volutpat nunc neque, eget fermentum leo tristique non. Morbi dui arcu, volutpat id sapien sed, placerat elementum odio. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In sagittis diam ligula, at mattis purus fermentum vel. Donec vel sollicitudin neque, sit amet consectetur urna. In hac habitasse platea dictumst. Sed porta ante nec vehicula pulvinar. Quisque bibendum nisl vitae mi auctor, blandit bibendum augue euismod. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed velit neque, consequat vestibulum ligula sit amet, congue scelerisque libero. In hac habitasse platea dictumst. Donec dapibus nisl at pretium dictum. Nulla facilisi. Suspendisse potenti.', 'it, debatt', 'nl2br', '2014-01-15 12:58:41', '2014-01-15 12:58:41', NULL, NULL);

--
-- Index för dumpade tabeller
--

--
-- Index för tabell `kmom07_Content`
--
ALTER TABLE `kmom07_Content`
 ADD PRIMARY KEY (`id`), ADD UNIQUE KEY `slug` (`slug`);

--
-- AUTO_INCREMENT för dumpade tabeller
--

--
-- AUTO_INCREMENT för tabell `kmom07_Content`
--
ALTER TABLE `kmom07_Content`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=9;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
